### ISSUE TITLE
new account cannot be found

### ISSUE THREAD

**Issue by engelhard61** [Capricoinofficial/copay#3]
Hello,

I have opened an account with copay capricoin and transferred CPC from vizionary to it.
This was also all ok, I see my CPC (643) but unfortunately I cannot open this account now.
When starting the PC a few days later, a new account was opened again. I can't import the existing account, because when I enter the recovery phrase (12 words), the note comes - import not possible, wallet recovery phrase is invalid - but the 12 words are correct.
Can you see where my account is and how I can access it again?
My E-Mail is REngelhard@gmx.de
Thanks for hepl.
Kind regards

Roland Engelhard

**Comment by CapricoinPlus** [comment]
when you say PC, do you mean you used the web-wallet located here (https://copay.capricoin.org/)? if so, you need to understand that your wallet is saved locally in your browser cache, if you clean your browser cache then your wallet will be deleted and you will need to import it again.

The good news is that you can't send funds to a newly created wallet before you backup it up, so what you need to do is to restore the wallet from the backup.

I will include step by step guide with screenshots to assist you:

1. Click on the + button to add a new wallet
2. Click on "Import wallet"
3. Type your recovery phrase you backed up earlier
7. Click on "Import wallet"

That is it! your wallet will be restored.

Soon we will release a Desktop version of Capricoin Copay as well so you don't have to go through this again, but keep in mind that every time you will clear your browser cache this will happen again, so please until then use the mobile wallet or the QT wallet if you plan on clearing your cache regularly.

![1](https://user-images.githubusercontent.com/58599015/84890904-5c1c4f00-b09b-11ea-902f-d5ca5a7f699f.png)
![2](https://user-images.githubusercontent.com/58599015/85019373-01ecbe00-b16f-11ea-82a6-297bc5ffbee1.png)
![3](https://user-images.githubusercontent.com/58599015/85019523-42e4d280-b16f-11ea-8823-14ea398741c3.png)

**Comment by engelhard61** [comment]
Hello,
thanks for answer for my first issue a few hours ago.
I tried to restore the wallet from the backup, but it doesn´t matter.
There is a note: error wallet recovery phrase not valid.
I´m sure the recovery phrase is correct. What can I do to restore my account ?

Is there any chance to import the wallet with the CPC on it ?

I had a Login password .

Thanks for anwer

Regards

Roland Engelhard

**Comment by engelhard61** [comment]
Hello, 
enclosed is the transfer voucher of the CPC from vizionary to my copay account.
Regards
Roland Engelhard

Vizionary

Reference: 5ede5914d38da
Wallet address: 8LRCDnUrYoczGocikExi2EerANbiL4hBPP
Amount to proceed: 643.53000000 CPC
Fee: 0.00050000 CPC
Amount: 643.52950000 CPC
Status: done
Created at: 9th June
Method: cpc-wallet
Reason: 3957d5feaa9722f9cc88638bf5a312edd3e43761b2d78373dc7ca033bb647528
Description: Viz

**Comment by CapricoinPlus** [comment]
Since this doesn't seem an issue with the Software itself, I would suggest that you contact us at support@capricoin.org and we will assist you from there.
