### ISSUE TITLE
new account can not be found #2

### ISSUE THREAD

**Issue by engelhard61** [Capricoinofficial/copay#4]
Hello,
thanks for answer for my first issue  a few hours ago.
I tried to restore the wallet from the backup, but it doesn´t matter.
There is a note: error wallet recovery phrase not valid. 
I´m sure the recovery phrase is correct. What can I do to restore my account ?

Is there any chance to import the wallet with the CPC on it ?

I had a Login password .

Thanks for anwer

Regards

Roland Engelhard

**Comment by CapricoinPlus** [comment]
Duplicate of #3
